name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    
    - name: Install dependencies
      run: npm install
    
    - name: Run contrast tests
      run: npm run test:contrast
    
    - name: Run color validation tests
      run: npm run test:colors
    
  package-vscode:
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js 18.x
      uses: actions/setup-node@v4
      with:
        node-version: 18.x
    
    - name: Package VS Code extension
      run: |
        npm install -g @vscode/vsce
        cd vscode
        vsce package
    
    - name: Upload VS Code extension artifact
      uses: actions/upload-artifact@v4
      with:
        name: vscode-extension
        path: vscode/*.vsix
